Repository NYTimes/Store, pull requests merged in 2018-07, with the labels that each got.

#346 issue #345 sample crashes on launch, create SampleRoomStore during on…
  app/src/main/java/com/nytimes/android/sample/SampleApp.kt
Labels: Type: Bug

#347 Convert sample to kotlin
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nytimes/android/sample/PersistingStoreActivity.kt
  app/src/main/java/com/nytimes/android/sample/SampleApp.kt
  app/src/main/java/com/nytimes/android/sample/activity/PersistingStoreActivity.java
  app/src/main/java/com/nytimes/android/sample/activity/StoreActivity.java
  app/src/main/java/com/nytimes/android/sample/data/model/Children.java
  app/src/main/java/com/nytimes/android/sample/data/model/Data.java
  app/src/main/java/com/nytimes/android/sample/data/model/Image.java
  app/src/main/java/com/nytimes/android/sample/data/model/Images.java
  app/src/main/java/com/nytimes/android/sample/data/model/Model.kt
  app/src/main/java/com/nytimes/android/sample/data/model/Post.java
  app/src/main/java/com/nytimes/android/sample/data/model/Preview.java
  app/src/main/java/com/nytimes/android/sample/data/model/RedditData.java
  app/src/main/java/com/nytimes/android/sample/data/model/package-info.java
  app/src/main/java/com/nytimes/android/sample/data/remote/Api.java
  app/src/main/java/com/nytimes/android/sample/data/remote/Api.kt
  app/src/main/java/com/nytimes/android/sample/reddit/PostAdapter.java
  app/src/main/java/com/nytimes/android/sample/reddit/PostAdapter.kt
  app/src/main/java/com/nytimes/android/sample/reddit/PostViewHolder.java
  app/src/main/java/com/nytimes/android/sample/reddit/PostViewHolder.kt
  app/src/main/java/com/nytimes/android/sample/util/BitmapTransform.java
  app/src/main/java/com/nytimes/android/sample/util/DeviceUtils.java
  app/src/main/res/layout/article_item.xml
  build.gradle
  buildsystem/dependencies.gradle
Labels: Kotlin, Type: Enhancement, Type: Quality Matters

#349 convert moshi middleware to kotlin
  build.gradle
  middleware-moshi/build.gradle
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiBufferedSourceAdapter.java
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiBufferedSourceAdapter.kt
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiParserFactory.java
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiParserFactory.kt
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiSourceParser.java
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiSourceParser.kt
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiStringParser.java
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiStringParser.kt
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiTransformerFactory.java
  middleware-moshi/src/main/java/com/nytimes/android/external/store3/middleware/moshi/MoshiTransformerFactory.kt
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/Model.kt
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/MoshiSourceParserTest.java
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/MoshiSourceParserTest.kt
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/MoshiStringParserStoreTest.java
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/MoshiStringParserStoreTest.kt
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/data/Bar.java
  middleware-moshi/src/test/java/com/nytimes/android/external/store3/middleware/moshi/data/Foo.java
Labels: Kotlin, Type: Feature, Type: Quality Matters

#352 convert first batch of filesystem module tests
  filesystem/build.gradle
  filesystem/src/test/java/com/nytimes/android/external/fs3/FSAllOperationTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/FSAllOperationTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/FilePersisterTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/FilePersisterTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/FileSystemRecordPersisterTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/FileSystemRecordPersisterTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/MultiTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/MultiTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/ObjectToSourceTransformerTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/ObjectToSourceTransformerTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/RecordPersisterTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/RecordPersisterTest.kt
Labels: Kotlin, Type: Enhancement, Type: Quality Matters

#354 second part of filesystem tests conversion to kotlin
  filesystem/src/test/java/com/nytimes/android/external/fs3/SourceDiskDaoStoreTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/SourceDiskDaoStoreTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/SourceFilerReaderWriterStoreTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/SourceFilerReaderWriterStoreTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/SourcePersisterTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/SourcePersisterTest1.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/StoreNetworkBeforeStaleFailTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/StoreNetworkBeforeStaleFailTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/StoreNetworkBeforeStaleTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/StoreNetworkBeforeStaleTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/UtilTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/UtilTest.kt
Labels: Kotlin, Type: Enhancement, Type: Quality Matters

#355 convert jackson middleware tests to kotlin
  buildsystem/dependencies.gradle
  middleware-jackson/build.gradle
  middleware-jackson/src/main/java/com/nytimes/android/external/store3/middleware/jackson/JacksonParserFactory.java
  middleware-jackson/src/main/java/com/nytimes/android/external/store3/middleware/jackson/JacksonReaderParser.java
  middleware-jackson/src/main/java/com/nytimes/android/external/store3/middleware/jackson/JacksonSourceParser.java
  middleware-jackson/src/main/java/com/nytimes/android/external/store3/middleware/jackson/JacksonStringParser.java
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/JacksonReaderParserStoreTest.java
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/JacksonReaderParserStoreTest.kt
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/JacksonSourceParserStoreTest.java
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/JacksonSourceParserStoreTest.kt
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/JacksonStringParserStoreTest.java
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/JacksonStringParserStoreTest.kt
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/Model.kt
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/data/Bar.java
  middleware-jackson/src/test/java/com/nytimes/android/external/store3/middleware/jackson/data/Foo.java
Labels: Kotlin, Type: Enhancement, Type: Quality Matters

#353 convert first half of store tests to kotlin
  store/build.gradle
  store/src/test/java/com/nytimes/android/external/store3/CharsetTest.java
  store/src/test/java/com/nytimes/android/external/store3/ClearStoreMemoryTest.java
  store/src/test/java/com/nytimes/android/external/store3/ClearStoreMemoryTest.kt
  store/src/test/java/com/nytimes/android/external/store3/ClearStoreTest.java
  store/src/test/java/com/nytimes/android/external/store3/ClearStoreTest.kt
  store/src/test/java/com/nytimes/android/external/store3/ClearingPersister.java
  store/src/test/java/com/nytimes/android/external/store3/DontCacheErrorsTest.java
  store/src/test/java/com/nytimes/android/external/store3/DontCacheErrorsTest1.kt
  store/src/test/java/com/nytimes/android/external/store3/GetRefreshingTest.java
  store/src/test/java/com/nytimes/android/external/store3/KeyParserTest.java
  store/src/test/java/com/nytimes/android/external/store3/KeyParserTest.kt
  store/src/test/java/com/nytimes/android/external/store3/NoNetworkTest.java
  store/src/test/java/com/nytimes/android/external/store3/NoNetworkTest.kt
Labels: Kotlin, Type: Enhancement, Type: Quality Matters

#356 last part of filesystem tests conversion
  build.gradle
  filesystem/src/test/java/com/nytimes/android/external/fs3/StoreRefreshWhenStaleTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/StoreRefreshWhenStaleTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/filesystem/BreadthFirstFileTreeIteratorTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/filesystem/BreadthFirstFileTreeIteratorTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/filesystem/FSFileTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/filesystem/FSFileTest.kt
  filesystem/src/test/java/com/nytimes/android/external/fs3/impl/SimpleTest.java
  filesystem/src/test/java/com/nytimes/android/external/fs3/impl/SimpleTest.kt
Labels: Kotlin, Type: Enhancement, Type: Quality Matters

#361 Add links to mentioned libraries
  README.md
Labels: Type: Enhancement, Type: Quality Matters

#362 Use implementation instead of compile
  README.md
Labels: Type: Enhancement, Type: Quality Matters

#360 Fix typos
  README.md
Labels: Type: Enhancement, Type: Quality Matters

#363 Update README.md
  README.md
Labels: Status: Review Needed, Type: Enhancement, Type: Quality Matters
